FROM openjdk
WORKDIR usr/lib
ADD ./target/FavouriteMovieService-0.0.1-SNAPSHOT.jar /usr/lib/FavouriteMovieService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","FavouriteMovieService-0.0.1-SNAPSHOT.jar"]
